buildrpm/bpftune.spec
bump to 0.1-2 after package review.
Orabug: 35385703
Reviewed-by: Laurence Rochfort <laurence.rochfort@oracle.com>
=> bpftune: packaging support

test/sample_legacy_test.sh, test/sample_test.sh
...since an old version of sample_tuner.so could be present.
=> sample_[legacy_]test should "make clean" before building sample

src/libbpftune.c, src/tcp_cong_tuner.c
module load was failing as we need CAP_SYS_MODULE, and as a result the tcp_bbr module wasnt loading
also needed to search in /lib/module/`uname -r`
needed to add capabilities around attach and fix error handling when link was not attached
=> tcp_cong_tuner: various fixes found for Ubuntu issues

src/Makefile, test/cap_test.sh, test/log_test.sh, test/service_test.sh, test/test_lib.sh
add ld.so.conf.d file for /usr/lib64 for bpftune.
also fix issues with tests for ubuntu such as assuming messages are in /var/log/messages (it's syslog for ubuntu)
Reported-by: https://github.com/twirrim
should resolve https://github.com/oracle-samples/bpftune/issues/11#top
=> bpftune: fix library search issues on Ubuntu

include/bpftune/bpftune.bpf.h, src/Makefile, src/libbpftune.c
as
Reported-by: https://github.com/MmartinezV2
should resolve
https://github.com/oracle-samples/bpftune/issues/14
=> fix compilation issues on debian

src/Makefile
as reported in
https://github.com/oracle-samples/bpftune/issues/12
we see compilation failures like
tcp_buffer_tuner.bpf.c:232:1: error: A call to built-in function '__stack_chk_fail' is not supported.
this looks like [1], which is fixed by disabling stack protection. Try this here too.
Reported-by: https://github.com/delvin-fil
=> bpftune: disable stack protection for BPF objects

buildrpm/bpftune.spec, src/Makefile
install /etc/ld.so.conf.d/bpftune.spec
=> fix pkg build

include/bpftune/libbpftune.h, sample_tuner/sample_tuner.c, src/neigh_table_tuner.c, src/net_buffer_tuner.c, src/netns_tuner.c, src/route_table_tuner.c, src/sysctl_tuner.c, src/tcp_buffer_tuner.c, src/tcp_cong_tuner.c
bpftune bpf initialization steps in macros in libbpftune.h (macros being used since bpf skeletons use object names in data structures) need to return status as without that we drive on if open/load/attach fail and this can trigger segmentation faults.
=> Status return

include/bpftune/libbpftune.h
we were dereferencing the skel pointer; it may be a error pointer value so check for this.
=> libbpftune: bpf open needs to handle errors

src/Makefile, src/netns_tuner.bpf.c, src/route_table_tuner.bpf.c, src/sysctl_tuner.bpf.c, src/tcp_cong_tuner.bpf.c
fix unused variable warnings
Suggested-by: https://github.com/pavlinux
=> bpftune: enable -Wall for clang compilation and fix issues

src/tcp_cong_tuner.bpf.c
...since bpf seems to object to loading a prog with this section
=> define global const char bbr array to avoid .rodata.str1.1 section

src/Makefile
make -j6 was failing; turns out we were bundling making of legacy and non-legacy objects in the same targets. it is better to split these into separate targets and add dependencies for all. with this change in place "make -j6" succeeds.
Reported-by: https://github.com/srcshelton
=> fix bpftune Makefile to support parallel make

Makefile, README.md, include/bpftune/bpftune.h, include/bpftune/libbpftune.h, src/Makefile, src/libbpftune.c, src/libbpftune.map, test/Makefile, test/strategy/Makefile, test/strategy/README.md, test/strategy/strategy_tuner.bpf.c, test/strategy/strategy_tuner.c, test/strategy_legacy_test.sh, test/strategy_test.sh
tuners can support multiple strategies; strategies should be set in the init() method via bpftune_strategies_add().  A strategy specifies a
- name
- description
- timeout
- evaluation function
- set of bpf program names in tuner associated with strategy
The current strategy runs until timeout, then the evaluation functions for all strategies are called; we then switch to the strategy with the highest evaluation.  See tests/strategy for an example of a tuner implementing multiple strategies.
=> add multiple strategy support

src/libbpftune.c
this may help get bpftune working with libbpf 0.5
=> libbpftune: remove need for bpf_object__for_each_program()

src/sysctl_tuner.bpf.c, src/sysctl_tuner.c
good to know who is changing sysctls when we disable tuner; log pid.
=> sysctl_tuner: log pid for sysctl modification

Makefile
We should create a SOURCES directory for rpmbuild, reproduce the problem:
```bash
$ rm -rf ~/rpmbuild
$ make pkg
...
git archive --format=tar --prefix=`rpmspec -q --queryformat="%{NAME}-%{VERSION}\n" buildrpm/bpftune.spec | head -1`/ -o /home/rongtao/rpmbuild/SOURCES/`rpmspec -q --queryformat="%{NAME}-%{VERSION}\n" buildrpm/bpftune.spec | head -1`.tar HEAD
fatal: could not open '/home/rongtao/rpmbuild/SOURCES/bpftune-0.1.tar' for writing: No such file or directory
```
=> make pkg: Fix SOURCES 'No such file or directory' error

.gitignore, include/bpftune/bpftune.bpf.h, include/bpftune/bpftune.h, include/bpftune/libbpftune.h, sample_tuner/Makefile, sample_tuner/sample_tuner.c, src/Makefile, src/bpftune.c, src/libbpftune.c, src/libbpftune.map, src/neigh_table_tuner.bpf.c, src/neigh_table_tuner.c, src/net_buffer_tuner.c, src/netns_tuner.c, src/probe.bpf.c, src/route_table_tuner.bpf.c, src/route_table_tuner.c, src/sysctl_tuner.bpf.c, src/sysctl_tuner.c, src/tcp_buffer_tuner.bpf.c, src/tcp_buffer_tuner.c, src/tcp_cong_tuner.bpf.c, src/tcp_cong_tuner.c, test/strategy/Makefile, test/strategy/strategy_tuner.c
on some systems BPF Type Format (BTF) info is not available.  Because we make extensive use of it, we need a separate set of BPF programs that work in a "no BTF" world; these cannot make use of Compile Once - Run Everywhere (CO-RE) relocations, so data structure offsets may be wrong for the running kernel, so warn the user.
Tuners cannot be supported in this mode because the likeliehood of such issues is nearly 100%; warn the user about this.
Reported-by: Stuart Shelton <https://github.com/srcshelton>
=> bpftune: support a "no BTF" mode of operation

src/libbpftune.c
when we get a signal during polling, we see
Aug 19 10:11:41 nixos-dell bpftune[7957]: ring_buffer__poll: Interrupted system call
This is not an error; it's just that the signal is delivered while we are polling, so skip error display for this case.
Reported by: Tungsten842 (https://github.com/Tungsten842)
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
=> libbpftune: do not print error when signal received

src/libbpftune.c
bpftune was exiting on suspend; the reason is we get an -EINTR while polling.  However because it is not a SIGINT/SIGTERM, we should not exit the polling routine for this error; the signal handling logic will do this for the signals we care about.
Tested via
$ systemctl suspend
bpftune service/program keeps running where it previously exited.
Reported by: Tungsten842 (https://github.com/Tungsten842)
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
=> bpftune: unexpected exit on suspend

include/bpftune/bpftune.bpf.h, include/bpftune/bpftune.h, include/bpftune/libbpftune.h, sample_tuner/Makefile, src/Makefile, src/libbpftune.c, test/strategy/Makefile
tuners that share bpf programs across strategies may want to have different behaviours depending on which strategy is active; assign strategy ids when strategies are added to tuner and expose to bpf progs via strategy_id variable; it is set as part of bpftune_bpf_open().
=> bpftune: expose strategy_id to tuner bpf programs

docs/bpftune.rst, include/bpftune/bpftune.h, include/bpftune/libbpftune.h, src/bpftune.c, src/libbpftune.c, src/libbpftune.map, test/Makefile, test/rollback_legacy_test.sh, test/rollback_test.sh
Support rollback mode where if bpftune is run with -R option, we roll back sysctl settings on exit.  Log will show us a summary of changes along with the values were rolled back; for example:
Aug 23 19:15:04 bpf bpftune[360835]: sysctl 'net.ipv4.tcp_wmem' changed from (4096 16384 16384 ) -> (4096 16384 2220415 )
Aug 23 19:15:04 bpf bpftune[360835]: Scenario 'need to increase TCP buffer size(s)' occurred for tunable 'net.ipv4.tcp_wmem' in global ns. Need to increase buffer size(s) to maximize throughput
Aug 23 19:15:04 bpf bpftune[360835]: Rolling back sysctl values for 'net.ipv4.tcp_wmem' from (4096 16384 2220415 ) to original values (4096 16384 16384 )...
=> bpftune: support rollback mode (-R) for bpftune

docs/bpftune-tcp-conn.rst, include/bpftune/bpftune.bpf.h, include/bpftune/bpftune.h, include/bpftune/libbpftune.h, include/bpftune/rl.h, src/libbpftune.c, src/neigh_table_tuner.bpf.c, src/netns_tuner.bpf.c, src/probe.bpf.c, src/route_table_tuner.bpf.c, src/tcp_buffer_tuner.bpf.c, src/tcp_conn_tuner.bpf.c, src/tcp_conn_tuner.c, src/tcp_conn_tuner.h, test/cong_legacy_test.sh, test/cong_test.sh, test/test_lib.sh
Previously, congestion control algoritm selection was done via a simple method of looking for packet loss on a per-connection basis and applying BBR if a limit was surpassed.
This approach has been replaced by using a reinforcement learning based algorithm which seeks to choose the congestion control algorithm that approaches optimal performance for the link; minimum RTT and delivery rate tuned to fill the pipe.  See bpftune-tcp-conn(8) for details.
The behaviour under loss is similar to before - BBR is selected - but it is selected based upon its optimal behaviour rather than via a hand-coded algorithm.  In normal network conditions, different algorithms can be selected; choices available currently are
- cubic
- BBR
- htcp
- dctcp
=> tcp_conn_tuner: move to using reinforcement learing approach

test/support_test.sh
6.5 and later support bpf trampoline for aarch64; update test
=> update support test for aarch64 bpf trampoline support

test/cong_legacy_test.sh, test/cong_test.sh
...which can happen with loss rate
=> make cong tests more robust to iperf3 failures

include/bpftune/libbpftune.h, src/libbpftune.c, src/libbpftune.map, src/tcp_conn_tuner.c, src/tcp_conn_tuner.h
is of the form
bpftune: Summary: scenario 'specify TCP congestion control algorithm' occurred 1 times for tunable 'TCP congestion control' in global ns. To optimize TCP performance, a TCP congestion control algorithm was chosen to mimimize round-trip time and maximize delivery rate.
=> tcp_conn_tuner: support summary output for non-debug case

test/cong_legacy_test.sh, test/cong_test.sh, test/test_lib.sh
combinations of 0/100ms latency, 0/10% packet loss
=> cong_test: support loss/latency combos

docs/Makefile, docs/bpftune-ip-frag.rst, src/Makefile, src/ip_frag_tuner.bpf.c, src/ip_frag_tuner.c, src/ip_frag_tuner.h, test/Makefile, test/frag_legacy_test.sh, test/frag_test.sh, test/test_lib.sh
For IPv[46] fragmentation reassembly, memory is capped at
net.ipv[46].ip[6]frag_high_thresh
Fragmentation reassembly can fail if this value is set too low; monitor for fragmentation reassembly and bump value if needed.
Avoid bumping it if assembly faiures constitute too high a proportion of reassembly events; this may signify a DoS.
Tests verify this works in non-global/global network namespaces.
To do: cap high_thresh?
=> IP fragmentation auto-tuning

src/ip_frag_tuner.bpf.c
we have bpf_per_cpu_ptr(), but it only works on v recent kernels for data structure fields; otherwise it fails verification. we will find another limit
=> ip frag tuner: cannot rely on MIBs, they are per-cpu

src/tcp_buffer_tuner.c
in some cases this static function is inlined; make it optional to avoid failure to attach tuner as a whole.
Reported-by: sm99c (https://github.com/sm9cc)
=> tcp_buffer_tuner: make tcp_sndbuf_expand optional

include/bpftune/libbpftune.h, sample_tuner/sample_tuner.bpf.c, sample_tuner/sample_tuner.c, src/libbpftune.c, src/net_buffer_tuner.c, src/netns_tuner.c, src/tcp_buffer_tuner.c
we can specify optional bpf progs at load time; simplify the code that does this and add logging; also add testing for this feature via the sample tuner.
=> fix optional support

src/tcp_buffer_tuner.bpf.c
TCP buffer tuner was failing to load on 6.9 and later.
CO-RE relocation for sk_userlocks in struct sock was the cause; the problem is sk_userlocks changes from a bitfield to a plain u8 and the vmlinux.h that was generated had the old representation. We can use a Linux version check to guard check of sk_userlocks.
Reported-by: HippieMitch <https://github.com/HippieMitch>
=> tcp_buffer_tuner: fix load failure for 6.9+

src/net_buffer_tuner.bpf.c, src/net_buffer_tuner.c
net_buffer_tuner.so was failing to load BTF due to a failure to find netdev_max_backlog ksym.
netdev_max_backlog was an int prior to 6.9 then it got added to a netdev hotpath struct; rather than using it in calculations retrieve the sysctl value and set a bpf global for use in bpf prog context; update it in userspace when we bump sysctl value.
Reported-by: HippieMitch <https://github.com/HippieMitch>
=> use bpf global for netdev_max_backlog as ksym changes in 6.9

src/Makefile, test/strategy/Makefile
Hey, Alan. 
Thanks for all the work on bpftune (and your informative talks on BTF :smile: ).
I wanted to begin the process of porting `bpftune` to support the BPF backend for gcc.
I started with the Makefile(s). 
On my fork, you can:
```
GCC_BPF=bpf-gcc make && sudo make install
```
It compiles successfully (and throws warnings due to ignoring unkown clang #pragmas).
Then you can run `bpftune` in legacy mode:
``` 
$ sudo bpftune -S     
bpftune: bpftune works in legacy mode
bpftune: bpftune supports per-netns policy (via netns cookie)
```
Below are the specifications for the machine I am testing on. 
I use upstream Debian for my work as much as possible:
```
$ bpf-gcc --version 
bpf-gcc (14.1.0-1+2) 14.1.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the …
```
=> Add support of gcc BPF backend

README.md, include/bpftune/libbpftune.h, src/Makefile
support install to /usr/lib instead of default /usr/lib64 through libdir=lib specification for make and make install targets
=> better handle nonstandard library install paths

src/bpftune.c, src/libbpftune.c
tuners can fail to load when their unstable tracing targets (kernel functions) are not present; improve messaging to reflect this.
=> improve tuner load error messaging

src/bpftune.c
Sometimes BTF is available to bpftune, but because it has been generated by a newer libbpf than has been used to build bpftune, it is not usable. The right answer is to rebuild bpftune with a newer libbpf in such cases. Update log messaging to suggest this.
=> bpftune: update error message to warn about incompatible BTF

src/Makefile
to work towards cross-compile support, allow specification of SRCARCH which is passed into BPF compilation targets via
-D__TARGET_ARCH_$(SRCARCH). -march=native is not needed.
=> src/Makefile: remove -march=native, allow override of SRCARCH

src/libbpftune.c
When we cannot enter a netns we should mark it as gone to avoid repeated errors
Reported-by: Rob Landers <landers.robert@gmail.com>
=> libbpftune: mark netns as _GONE if we cannot setns()

include/bpftune/libbpftune.h, src/libbpftune.c
when matching netns cookies with netns, we iterate over all netns and setns() to retrieve the cookie. This can fail but currently we dump error messages in such cases. Error messaging should be reserved for the case where we are entering the netns to either read or write sysctls.  So add a bool quiet param to bpftune_netns_set().
Reported-by: Rob Landers <landers.robert@gmail.com>
=> libbpftune: support quiet mode for bpftune_netns_set()

src/Makefile
libbpftune should depend on headers so that if they change we rebuild bpftune.  Also include the git SHA string in the version where an explicit version is not provided.
=> improve makefile dependencies

src/libbpftune.c
Roger reported a segmentation fault in tcp_buffer_tuner. Examining the state of the tuner we were handling an event when in manual (i.e. off) state.  The event handler for a tuner should only be called if the tuner is active.
Reported by: Roger Knobbe (https://github.com/rknobbe)
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
=> libbpftune: only send events to active tuners

src/libbpftune.c
we were logging changes for non-global ns using cached global ns values; these are used for global ns rollback only.
=> libbpftune: fix logging for non-global netns

src/libbpftune.c
Causes issues on aarch64; rework to pass va_args *
=> libbpftune: fix va_args handling in scenario logging

test/many_netns_legacy_test.sh, test/many_netns_test.sh, test/rmem_legacy_test.sh, test/rmem_test.sh, test/test_lib.sh, test/wmem_legacy_test.sh, test/wmem_test.sh
log bpftune output to test log so that it can be displayed on error when VERBOSE=1
=> test: improve debugging for wmem/rmem/many_netns tests

src/ip_frag_tuner.c
cannot be set in a non-global ns
=> ip_frag_tuner: tunables are not namespaced

test/Makefile, test/netns_legacy_test.sh, test/netns_test.sh, test/podman_globalonly_legacy_test.sh, test/podman_globalonly_test.sh, test/test_lib.sh
first tests verify that changes observed in a non-global podman netns for a global-only tunable trigger global tunable changes; in this case fragmentation memory limits trigger increase in fragmentation high threshold.
=> test: add podman tests

test/frag_legacy_test.sh, test/frag_test.sh
frag changes are global ns only, so monitor there exclusively
=> test: fix frag tests

src/bpftune.c
Need to ensure suffix is ".so" without additional following chars.
Reported-by: Bernd Zeimetz <bzed@debian.org>
=> libbpftune: ensure we only init ".so" objects

README.md
Reported-by:  Tessa Nordgren <https://github.com/nergdron>
=> note need for libnl-route-3-dev for Debian

docs/bpftune-tcp-conn.rst, src/tcp_conn_tuner.bpf.c, src/tcp_conn_tuner.c, src/tcp_conn_tuner.h, test/Makefile, test/file_download_legacy_test.sh, test/file_download_test.sh, test/test_lib.sh
....if these exceed 1/32 of packets sent.  Also only apply RL techniques for connections we repeatedly use; this saves us trying to apply RL to cases where we do not have enough data to make good choices.
Add file download test using python3 http.server; it allows us to show BBR kicking in for connections where loss/latency are induced via netem.
=> tcp_conn_tuner: notice retransmit events for tcp conn, apply BBR

include/bpftune/bpftune.bpf.h, src/tcp_buffer_tuner.bpf.c, src/tcp_buffer_tuner.c
Please keep in mind that I did not test the result, but it compiles.
Fixes #131
=> Fix compiling on i386

docs/bpftune-tcp-conn.rst, src/tcp_conn_tuner.bpf.c, src/tcp_conn_tuner.h, test/file_download_legacy_test.sh, test/file_download_test.sh
this is a ~1.5% drop rate which experiments show BBR to perform much better with than cubic or other algorithms since BBR does not just use loss as a signal.
Also update download tests to use a larger set of loss/latencies.
=> reduce drop threshold to 1/64th of segs sent

src/net_buffer_tuner.bpf.c, test/budget_test.sh
because we can have net_rx_action() run on different processors we may have cases where we do not see increases for every sample but the increases do happen for different cpus; as such, relax criteria for time_squeezed to simply increase from one sample to the next.
Also fix budget test to verify budget + budget_usecs increase.
=> netdev budget: fix criteria for budget increase

include/bpftune/bpftune.h, src/libbpftune.c, src/tcp_conn_tuner.c
most tuners we can summarize via sysctl data, but for tcp conn we need a callback to summarize; add an optional one to tuners.
=> add optional summarize function to tuners

include/bpftune/bpftune.bpf.h, include/bpftune/vmlinux_aarch64.h, include/bpftune/vmlinux_x86_64.h, src/Makefile
support gcc-bpf preserve access index in vmlinux_<arch>.h
=> more gcc-bpf-related changes

src/Makefile, test/strategy/Makefile
...as without this compilation fails for latest gcc bpf
=> to support GCC_BPF, and -std=gnu17

src/net_buffer_tuner.bpf.c, src/netns_tuner.bpf.c
warnings around uninitialized vars etc.
=> eliminate warnings when building with gcc-bpf

src/tcp_buffer_tuner.bpf.c
CO-RE does support bitfields via BPF_CORE_READ_BITFIELD(); switch to using that for < 6.9 kernels where sk_userlocks is a 4-bit bitfield.
Reported-by: Xyz00777 <https://github.com/Xyz00777>
Reported-by: Delyan Kratunov <https://github.com/dkratunov>
=> tcp_buffer_tuner: fix bitfield access on older kernels

CONTRIBUTING.md, include/bpftune/bpftune.bpf.h, include/bpftune/bpftune.h, include/bpftune/libbpftune.h, src/libbpftune.c, src/net_buffer_tuner.bpf.c, src/net_buffer_tuner.c, src/tcp_buffer_tuner.bpf.c, src/tcp_buffer_tuner.c, test/Makefile, test/rate_test.sh
One approach to reducing overhead is to introduce sampling; i.e. a high-frequency program bails early and only does more expensive work for 1 out of every N invokations.  bpftune has adaptive sampling to support this.  It works as follows.
In your BPF object, add a struct bpftune_sample variable for the BPF program you wish to sample.  For example in tcp_buffer_tuner.bpf.c we have
```
struct bpftune_sample rcv_space_sample = { };
```
Since tcp_rcv_space_adjust() is called frequently, add the following early in function lifetime:
```
bpftune_sample(rcv_space_sample);
```
The above will bail if it is not the Nth invokation of the program. Note that N is usually bpftune_sample_rate - default 4 - but will be adaptively adjusted if the program runs too frequently.  Too frequently is 2N …
=> bpftune: add adaptive sampling

test/Makefile, test/stress_ng_test.sh, test/test_lib.sh
tests that compare bogo ops/s for 10, 1000 sockets in baseline, bpftune running modes and examine which tunables were updated.
=> test: add stress-ng tests

src/libbpftune.c, src/tcp_conn_tuner.c, test/query_test.sh
these changes fix issues in rollback and provide a "rollback" query which gives a paste-able set of commands to restore to pre-bpftune sysctl settings
=> Rollback fix

include/bpftune/libbpftune.h, src/libbpftune.c, src/libbpftune.map, src/tcp_buffer_tuner.bpf.c, src/tcp_buffer_tuner.c, test/many_netns_legacy_test.sh, test/many_netns_test.sh
...since we can get values via /proc/net/netstat, and func signature changes between kernel versions making fexit infeasible. Also clean up many_netns_test to be more robust.
=> tcp_buffer_tuner: remove tracing for cookie v[46] check

test/stress_ng_test.sh
1000 socket test is too much for some VMs, limit to 500.
=> stress-ng-test: limit to 500 socket test

docs/bpftune-tcp-conn.rst, src/tcp_conn_tuner.bpf.c, src/tcp_conn_tuner.c, src/tcp_conn_tuner.h
...for lossy connections if net.ipv4.tcp_thin_linear_timeouts = 0. This ensures that thin TCP connections will avoid exponential backoff costs in cases of loss so be more responsive.
=> tcp_conn_tuner: set thin linear timeouts on a per-conn basis

README.md
Adds an Ansible download, built, install and start play.
I tested it on Debian 12, Ubuntu 22, Rocky Linux 9.
The only Problem is, that on some fedoara based systems the libbpf-devel package is not provided in the default repository. I found a side where you can look through the different distributions and you get the information what repo you have to add. I thought also about implementing the system detection, scrabbing it from the site and usint it as a variable, but that would have been to difficult for me to do.
I hope it is self explaining what it does :)
=> Add Ansible Play to download, built, install and start bpftune

src/tcp_buffer_tuner.c
ensure it is therefore marked as optional.
Reported-by: NullX47 (https://github.com/NullX47)
=> tcp_buffer_tuner: tcp_syn_flood_action may be inlined/optimized

include/bpftune/libbpftune.h, src/libbpftune.c
when optional programs are included in a tuner and the initial (load all programs) stage fails, we fall back to loading only the non-optional progs.  However we still get error messages from the first case, which makes it look like the tuner ultimately failed to load.  Add a quiet option for tuner load in the case of initial load all programs phase where we have optional programs for later retry.
Reported-by: NullX47 (https://github.com/NullX47)
=> libbpftune: only show errors on optional prog reload

docs/bpftune.rst, src/libbpftune.c, src/netns_tuner.c, src/tcp_conn_tuner.c, test/query_test.sh, test/test_lib.sh
this will be hepful in adding PCP support as JSON format is easier to parse.  Two new queries are added:
jtunables              show list of tunables(json)
jstatus            show status of tunables(json)
=> libbpftune: add support for json queries of tunables, state

src/libbpftune.c
Because the clang analyzer does not look into libraries, it thinks the BPF skeleton objects calloc()ed in BPF skeletons are not freed because a wrapper function is used to free them.  Work around this to convince the analyzer the memory is freed since we cannot change the bpftool-generated skeletons.
=> libbpftune: quiet clang analyzer complaints about unfreed memory
